FROM php:8.5-fpm-alpine

RUN apk add --no-cache icu-dev libzip-dev \
    && docker-php-ext-install intl opcache pdo_mysql zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

CMD ["php-fpm"]
